language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  on:
    branch: master
